---
title: "Thesis figures"
subtitle: "STA 610"
author: "Samuel Richards"
output:
  # pdf_document:       #caution when recreating the .tex file as it may overwrite any changes made in Overleaf
  #   keep_tex: TRUE
  html_document:
    toc: yes
    toc_float: yes
    code_folding: hide
    number_sections: no
---

<!--Use this file for a separate project; modify it for Thesis when it is in Overleaf -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = 'Figures/')
library(tidyverse)
library(gridExtra)
```

# Artificial Neural Networks

## Step Function
```{r step-function, echo=FALSE}
step <- function(x){
  ifelse (x <= 0,0,1) 
}

f <- seq(-8,8, length=1000)

plot(f,step(f), type = 's', lwd = 8, main="Step Function", xlab = " ", ylab = " ", ylim = c(0,1), col = "turquoise", frame.plot = T)
```


## Sigmid Function
```{r sigmoid-function, echo=FALSE}
sigmoid <- function(x){
  return(1 / (1 + exp(-x)))
}

f <- seq(-8,8, length=1000)

plot(f,sigmoid(f), main="Sigmoid Function", xlab = " ", ylab = " ", ylim = c(0,1), col = "turquoise", frame.plot = T)
```


## Other Activation Functions
```{r other-activation-functions, echo=FALSE}
relu <- function(x){
  ifelse (x<0,0,x) 
}

f <- seq(-8,8, length=1000)

plot(f,tanh(f), main="Hyperbolic Tangent", xlab = " ", ylab = " ", col = "turquoise")
plot(f,relu(f), main="ReLU", xlab = " ", ylab = " ", col = "turquoise")
```



## Gradient Descent

### 2-D example
```{r grad_desc_2D, echo=FALSE}
f <- seq(-8,8, length=1000)

plot(f,2*f^3+10*f^2, main=" ", xlab = " ", ylab = " ", col = "darkred")
```

### 3-D example
```{r grad_desc, eval=FALSE, include=FALSE}
#Only use the final output from the 2D animation and the 3D output of the relevant function
# turned off so not to overflow figures folder

library(animation) 

ani.options(interval = 0.8, nmax = 50)
f1 = function(x, y) 1/2*x^2 + 4*sin(y)

xx = grad.desc(f1, pi * c(-2, -2, 2, 2), c(-2 * pi, 2))

xx$persp(col = "lightblue", theta = 30, phi = 30)
```






